---
deployment:
 tasks:
 - export DEPLOYPATH=/home/esteves5/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH
 - /bin/cp -R imgs $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH